# -*- coding: utf-8 -*-
"""codigoBase.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_QbzaKI3kBOXM471cE6iJTXreKS9fGpb
"""

import pandas as pd
import plotly.express as px
import streamlit as st


# DEFININDO O ENDEREÇO DO CONJUNTO DE DADOS
path = 'https://raw.githubusercontent.com/wcota/covid19br/master/cases-brazil-states.csv'

# CARREGANDO O DATASET
df = pd.read_csv(path)

# ATRIBUINDO NOVOS NOMES PARA ALGUMAS COLUNAS
new_columns = {
    'newDeaths': 'Novos óbitos',
    'newCases': 'Novos casos',
    'deaths_per_100k_inhabitants': 'Óbitos por 100 mil habitantes',
    'totalCases_per_100k_inhabitants': 'Casos por 100 mil habitantes'
}

df.rename(columns = new_columns, inplace = True)


# SELEÇÃO DE ESTADO
estados = list(df['state'].unique())
state = st.sidebar.selectbox('Qual estado?', estados)


# SELEÇÃO DE COLUNA
colunas =  ['Novos óbitos', 'Novos casos', 'Óbitos por 100 mil habitantes', 'Casos por 100 mil habitantes']
column = st.sidebar.selectbox('Qual tipo de informação?', colunas)


# SELEÇÃO DAS LINHAS QUE PERTENCEM AO ESTADO
df = df[df['state'] == state]


# PLOT DO GRÁFICO
fig = px.line(df,
              x = 'date',
              y = column,
              title = column + ' - ' + state)

fig.update_layout(xaxis_title = 'Data',
                  yaxis_title = column.upper(),
                  title = {'x': 0.5})

st.title('DADOS COVID - BRASIL')
st.write('Nessa aplicação, o usuário tem a opção de escolher o estado e o tipo de informação para mostrar o gráfico')

st.plotly_chart(fig, use_container_width=True)

st.caption('Os dados foram obtidos a partir do site: https://github.com/wcota/covid19br')